import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { Icon } from "@/components/ui/icon";
import { FeedbackBanner } from "@/features/crm/components/feedback-banner";
import { NoOrganizationState } from "@/features/crm/components/no-organization-state";
import { getCrmContext } from "@/features/crm/server/context";
import { getCrmMembers } from "@/features/crm/server/queries";
import { isUuid } from "@/features/crm/validation";
import { createProposalRevisionAction, transitionProposalAction } from "@/features/proposals/actions";
import { AttachmentManager } from "@/features/proposals/components/attachment-manager";
import { ProposalActions } from "@/features/proposals/components/proposal-actions";
import { ProposalHistory } from "@/features/proposals/components/proposal-history";
import { ProposalStatusBadge } from "@/features/proposals/components/proposal-status-badge";
import { formatCurrency, formatProposalDate } from "@/features/proposals/format";
import { getProposalById } from "@/features/proposals/server/queries";

export const metadata: Metadata = { title: "Detalhes da proposta" };
function Detail({ label, children }: { label: string; children: ReactNode }) { return <div><dt className="text-xs font-medium text-subtle">{label}</dt><dd className="mt-1 text-sm text-strong">{children || "—"}</dd></div>; }

export default async function ProposalDetailPage({ params, searchParams }: { params: Promise<{ proposalId: string }>; searchParams: Promise<{ success?: string | string[] }> }) {
  const { proposalId } = await params; if (!isUuid(proposalId)) notFound();
  const context = await getCrmContext(); if (context.status !== "ready") return <NoOrganizationState />;
  const [proposal, members] = await Promise.all([getProposalById(context.supabase, context.organization.id, proposalId), getCrmMembers(context.supabase, context.organization.id, context.user)]); if (!proposal) notFound();
  const query = await searchParams; const success = Array.isArray(query.success) ? query.success[0] : query.success;
  const canApprove = context.organization.role === "owner" || context.organization.role === "admin";
  const memberNames = Object.fromEntries(members.map((member) => [member.userId, member.displayName]));
  return <>
    <Link href="/propostas" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-muted hover:text-brand"><Icon name="arrowLeft" className="size-4" /> Voltar para propostas</Link><FeedbackBanner code={success} />
    <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-brand">{proposal.code} · Revisão {proposal.revision_number}</p><ProposalStatusBadge status={proposal.status} /></div><h1 className="mt-2 text-[26px] font-semibold tracking-[-0.035em] text-strong sm:text-[30px]">{proposal.title}</h1><p className="mt-2 text-sm text-muted">{proposal.clientName}</p></div>{proposal.status === "draft" && <Link href={`/propostas/${proposal.id}/editar`} className="inline-flex h-10 w-fit items-center gap-2 rounded-xl border border-line bg-surface px-4 text-sm font-semibold text-muted hover:bg-soft"><Icon name="edit" className="size-4" /> Editar rascunho</Link>}</header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,0.75fr)]"><div className="space-y-5">
      <section className="rounded-2xl border border-line bg-surface p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold text-strong">Resumo comercial</h2><p className="mt-1 text-sm text-muted">Valores oficiais calculados pelo PostgreSQL.</p></div><p className="text-xl font-semibold text-brand">{formatCurrency(proposal.total_amount)}</p></div><dl className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Detail label="Cliente"><Link className="font-semibold text-brand hover:underline" href={`/clientes/${proposal.client_id}`}>{proposal.clientName}</Link></Detail><Detail label="Oportunidade">{proposal.opportunity?.title}</Detail><Detail label="Validade">{formatProposalDate(proposal.valid_until)}</Detail><Detail label="Criada em">{formatProposalDate(proposal.created_at, true)}</Detail><Detail label="Enviada em">{formatProposalDate(proposal.sent_at, true)}</Detail><Detail label="Aprovada em">{formatProposalDate(proposal.approved_at, true)}</Detail><Detail label="Rejeitada em">{formatProposalDate(proposal.rejected_at, true)}</Detail><Detail label="Prazo de execução">{proposal.execution_deadline}</Detail><Detail label="Condições de pagamento">{proposal.payment_terms}</Detail></dl>{proposal.rejection_reason && <div className="mt-5 rounded-xl bg-danger-soft p-4 text-sm text-danger"><strong>Motivo da rejeição:</strong> {proposal.rejection_reason}</div>}{proposal.notes && <div className="mt-5 border-t border-line pt-5"><p className="text-xs font-medium text-subtle">Observações</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted">{proposal.notes}</p></div>}</section>
      <section className="rounded-2xl border border-line bg-surface p-5 sm:p-6"><h2 className="text-base font-semibold text-strong">Itens</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-line text-xs text-subtle"><tr><th className="pb-3">Descrição</th><th className="pb-3 text-right">Qtd.</th><th className="pb-3 text-right">Unitário</th><th className="pb-3 text-right">Desconto</th><th className="pb-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-line">{proposal.items.map((item) => <tr key={item.id}><td className="py-3"><p className="font-semibold text-strong">{item.service_name_snapshot}</p><p className="mt-1 text-muted">{item.description}</p></td><td className="py-3 text-right text-muted">{Number(item.quantity).toLocaleString("pt-BR")}</td><td className="py-3 text-right text-muted">{formatCurrency(item.unit_price)}</td><td className="py-3 text-right text-muted">{formatCurrency(item.discount_amount)}</td><td className="py-3 text-right font-semibold text-strong">{formatCurrency(item.line_total)}</td></tr>)}</tbody><tfoot><tr className="border-t border-line"><td colSpan={4} className="pt-4 text-right font-semibold text-strong">Total</td><td className="pt-4 text-right text-base font-semibold text-brand">{formatCurrency(proposal.total_amount)}</td></tr></tfoot></table></div></section>
      <section className="rounded-2xl border border-line bg-surface p-5 sm:p-6"><h2 className="text-base font-semibold text-strong">Documentos PDF</h2><p className="mb-5 mt-1 text-sm text-muted">Arquivos privados, versionados e acessíveis por link temporário.</p><AttachmentManager proposalId={proposal.id} attachments={proposal.attachments} authorNames={memberNames} currentUserId={context.user.id} role={context.organization.role} /></section>
    </div><aside className="space-y-5"><section className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-base font-semibold text-strong">Ações comerciais</h2><p className="mb-4 mt-1 text-sm text-muted">As transições são validadas novamente no servidor e no banco.</p><ProposalActions status={proposal.status} canApprove={canApprove} transition={transitionProposalAction.bind(null, proposal.id)} revision={createProposalRevisionAction.bind(null, proposal.id)} />{!canApprove && ["sent", "negotiating"].includes(proposal.status) && <p className="mt-3 text-xs text-subtle">A aprovação é exclusiva de owner e admin.</p>}</section><section className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-base font-semibold text-strong">Histórico</h2><div className="mt-5"><ProposalHistory events={proposal.events} actorNames={memberNames} /></div></section></aside></div>
  </>;
}
